### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by JoeyTPChou** [PygmalionAI/training-code#12]
Hi,

I am curious about these 2 assertions
1. https://github.com/PygmalionAI/training-code/blob/main/training/monkeypatches/xformers_gpt.py#LL30C17-L30C17
2. https://github.com/PygmalionAI/training-code/blob/main/training/monkeypatches/xformers_gpt.py#L50

What is (are) the reason?

Thanks,
Joey

**Comment by TearGosling** [comment]
Hi there! Sorry for the long wait, didn't see this before.
1. This assertion is actually part of code taken from HuggingFace's `optimum` library, [here](https://github.com/huggingface/optimum/blob/b9ec1ec72aaf3e0f7c75f2fd572a6557ca050416/optimum/bettertransformer/models/attention.py#L53). I am not entirely sure why they have done this, but my assumption is that something about PyTorch's `scaled_dot_product_attention` requires special treatment to be done to the input tensors if those conditions are fulfilled.
2. This was meant as a temporary assertion. Xformers does not play nice with `transformers` models in general, and upping the batch size beyond 1 introduces various errors. Still need to figure this out, but there's been a lot of stuff I've been preoccupied by recently.

Thanks for asking!
